# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wdAC84Km7YvPCpVg9cLQ1DYF3KUzOaAo
"""

!pip install pandas numpy scikit-learn seaborn

!pip install tensorflow[and-cuda]

import tensorflow as tf

devices = tf.config.list_physical_devices('GPU')
if len(devices) > 0:
    print("TensorFlow is configured to use GPU(s):")
    for device in devices:
        print(device)
else:
    print("TensorFlow is not configured to use any GPU.")

# ======================================================
# IMPORTS
# ======================================================
import pandas as pd
import numpy as np
import re
import json
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

# ======================================================
# ADDITIONAL IMPORTS FOR CALLBACKS
# ======================================================
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau
from tensorflow.keras.layers import Bidirectional, BatchNormalization

import warnings
warnings.filterwarnings('ignore')

# ======================================================
# 1. DATA LOADING & ERROR HANDLING
# ======================================================
file_path = "Modsec-WP.xlsx"

df = pd.read_excel(file_path)
print(f"✔ Data loaded successfully!")
print(f"📊 Dataset shape: {df.shape[0]} rows × {df.shape[1]} columns")
print("\n" + "="*60)

df.head()

# ======================================================
# 2. DATA INSPECTION & VALIDATION
# ======================================================

print("=" * 60)
print("DATA QUALITY REPORT")
print("=" * 60)

# 1. Check missing values
print("\n1️⃣ Missing Values:")
missing = df.isnull().sum()
if missing.sum() == 0:
    print("   ✔ No missing values found")
else:
    print(missing[missing > 0])
    print(f"   ⚠ Total missing: {missing.sum()}")

# 2. Check duplicate rows
print("\n2️⃣ Duplicate Rows:")
duplicates = df.duplicated().sum()
if duplicates == 0:
    print("   ✔ No duplicates found")
else:
    print(f"   ⚠ Found {duplicates} duplicate rows ({duplicates/len(df)*100:.2f}%)")
    # Optional: Remove duplicates
    # df = df.drop_duplicates()

# 3. Check label distribution
print("\n3️⃣ Label Distribution:")
label_counts = df['label'].value_counts()
print(label_counts)
print("\nPercentage:")
print((label_counts / len(df) * 100).round(2))

# Check if imbalanced
max_ratio = label_counts.max() / label_counts.min()
if max_ratio > 3:
    print(f"\n   ⚠ WARNING: Imbalanced dataset detected! (ratio: {max_ratio:.2f}:1)")
    print("   Consider using class_weight or SMOTE for balancing")
else:
    print(f"\n   ✔ Dataset is relatively balanced (ratio: {max_ratio:.2f}:1)")

# 4. Visualize label distribution
plt.figure(figsize=(10, 5))
label_counts.plot(kind='bar', color='steelblue')
plt.title('Label Distribution')
plt.xlabel('Attack Type')
plt.ylabel('Count')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig("label_distribution.png", dpi=300)
plt.show()
print("✔ Label distribution plot saved")

print("\n" + "=" * 60)

# ======================================================
# 3. TEXT PREPROCESSING FUNCTIONS
# ======================================================

# def clean_text(text):
#     """
#     Clean text data for security log analysis
#     - Convert to lowercase
#     - Remove excessive whitespace
#     - Keep important security-related characters
#     """
#     if pd.isna(text):
#         return ""

#     text = str(text).lower()

#     # Remove excessive whitespace
#     text = re.sub(r'\s+', ' ', text)

#     # Remove leading/trailing whitespace
#     text = text.strip()

#     return text

# ======================================================
# 4. FEATURE ENGINEERING (Original - 5 Features)
# ======================================================

# Combine 5 original columns
df["text"] = (
    df["request_useragent"].astype(str) + " " +
    df["request_line"].astype(str) + " " +
    df["action_message"].astype(str) + " " +
    df["message_description"].astype(str) + " " +
    df["full_message_line"].astype(str)
)

print(f"\n📝 Sample text (first 300 chars):\n{df['text'].iloc[0][:300]}...")
print("\n" + "="*60)

# ======================================================
# 4B. HANDLING IMBALANCED DATASET - UNDERSAMPLING
# ======================================================

print("=" * 60)
print("UNDERSAMPLING IMBALANCED DATASET")
print("=" * 60)

# Check current distribution
print("\n📊 Original Label Distribution:")
original_counts = df['label'].value_counts()
print(original_counts)
print(f"\nTotal rows: {len(df)}")

# Define target count for SQLi class
TARGET_SQLI_COUNT = 8000

# Separate SQLi and non-SQLi data
df_sqli = df[df['label'] == 'sqli']
df_other = df[df['label'] != 'sqli']

print(f"\n🔍 SQLi rows before: {len(df_sqli)}")
print(f"🔍 Other rows: {len(df_other)}")

# Undersample SQLi class
if len(df_sqli) > TARGET_SQLI_COUNT:
    df_sqli_sampled = df_sqli.sample(n=TARGET_SQLI_COUNT, random_state=42)
    print(f"\n✂ Undersampling SQLi from {len(df_sqli)} to {TARGET_SQLI_COUNT} rows")
else:
    df_sqli_sampled = df_sqli
    print(f"\n⚠ SQLi class already has {len(df_sqli)} rows (less than target)")

# Combine back
df = pd.concat([df_sqli_sampled, df_other], ignore_index=True)

# Shuffle the dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\n✔ Dataset resampled and shuffled")
print(f"\n📊 New Label Distribution:")
new_counts = df['label'].value_counts()
print(new_counts)
print(f"\nTotal rows: {len(df)}")

# Calculate new balance ratio
max_ratio = new_counts.max() / new_counts.min()
print(f"\n📈 New imbalance ratio: {max_ratio:.2f}:1")

# Visualize comparison
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Before
axes[0].bar(original_counts.index, original_counts.values, color='lightcoral', edgecolor='black')
axes[0].set_title('Label Distribution - BEFORE Undersampling', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Attack Type')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=45)
axes[0].grid(axis='y', alpha=0.3)

# After
axes[1].bar(new_counts.index, new_counts.values, color='steelblue', edgecolor='black')
axes[1].set_title('Label Distribution - AFTER Undersampling', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Attack Type')
axes[1].set_ylabel('Count')
axes[1].tick_params(axis='x', rotation=45)
axes[1].grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig("undersampling_comparison.png", dpi=300, bbox_inches='tight')
plt.show()

print("\n✔ Comparison plot saved: undersampling_comparison.png")
print("=" * 60)

# ======================================================
# 5. SEQUENCE LENGTH ANALYSIS
# ======================================================

print("Analyzing text sequence lengths...")

# Calculate word count per text
df['word_count'] = df['text'].apply(lambda x: len(x.split()))

# Statistics
print("\nSequence Length Statistics:")
print(df['word_count'].describe())

# Calculate optimal MAX_LEN based on percentiles
percentile_95 = int(df['word_count'].quantile(0.95))
percentile_99 = int(df['word_count'].quantile(0.99))

print(f"\n95th percentile: {percentile_95} words")
print(f"99th percentile: {percentile_99} words")
print(f"\nRecommended MAX_LEN: {percentile_95} (covers 95% of data)")

# Visualize distribution
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.hist(df['word_count'], bins=50, color='steelblue', edgecolor='black')
plt.axvline(percentile_95, color='red', linestyle='--', label=f'95th percentile ({percentile_95})')
plt.axvline(percentile_99, color='orange', linestyle='--', label=f'99th percentile ({percentile_99})')
plt.xlabel('Number of Words')
plt.ylabel('Frequency')
plt.title('Distribution of Sequence Lengths')
plt.legend()

plt.subplot(1, 2, 2)
plt.boxplot(df['word_count'], vert=True)
plt.ylabel('Number of Words')
plt.title('Boxplot of Sequence Lengths')

plt.tight_layout()
plt.savefig("sequence_length_analysis.png", dpi=300)
plt.show()

print("Sequence length analysis plot saved")
print("\n" + "="*60)

# Drop temporary column
df = df.drop('word_count', axis=1)

# ======================================================
# 6. LABEL ENCODING
# ======================================================

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(df["label"])
y = to_categorical(y)

print(f"Labels encoded")
print(f"Number of classes: {len(label_encoder.classes_)}")
print(f"Classes: {label_encoder.classes_}")
print("\n" + "="*60)

# ======================================================
# 7. TOKENIZATION & PADDING
# ======================================================

# Hyperparameters (based on analysis)
MAX_WORDS = 20000     # Vocabulary size
MAX_LEN = 200         # Maximum sequence length (adjust based on sequence analysis above)

print(f"Hyperparameters:")
print(f"   MAX_WORDS: {MAX_WORDS}")
print(f"   MAX_LEN: {MAX_LEN}")

# Tokenization
print("\n Tokenizing text...")
tokenizer = Tokenizer(num_words=MAX_WORDS,)
tokenizer.fit_on_texts(df["text"])

# Convert to sequences
X = tokenizer.texts_to_sequences(df["text"])

# Padding
X = pad_sequences(X, maxlen=MAX_LEN)

print(f"Tokenization complete")
print(f"Vocabulary size: {len(tokenizer.word_index)}")
print(f"Final sequence shape: {X.shape}")
print("\n" + "="*60)

# ======================================================
# 8. TRAIN-TEST SPLIT (Stratified)
# ======================================================

# Use stratified split to maintain label distribution
y_labels = np.argmax(y, axis=1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y_labels  # ✨ Stratified split
)

print(f"Data split complete")
print(f"Training set: {X_train.shape[0]} samples")
print(f"Test set: {X_test.shape[0]} samples")

# Verify label distribution
print("\nLabel distribution in splits:")
train_dist = np.argmax(y_train, axis=1)
test_dist = np.argmax(y_test, axis=1)

print("\nTraining set:")
for i, label in enumerate(label_encoder.classes_):
    count = (train_dist == i).sum()
    print(f"   {label}: {count} ({count/len(train_dist)*100:.1f}%)")

print("\nTest set:")
for i, label in enumerate(label_encoder.classes_):
    count = (test_dist == i).sum()
    print(f"   {label}: {count} ({count/len(test_dist)*100:.1f}%)")

print("\n" + "="*60)

"""--------------------------------------------------------------------------------"""

# ======================================================
# 9. MODEL ARCHITECTURE (Improved)
# ======================================================

# model = Sequential([
#     # Embedding layer
#     Embedding(input_dim=MAX_WORDS,
#               output_dim=128,
#               input_length=MAX_LEN,
#               name='embedding'),

#     # LSTM with return sequences
#     LSTM(128, return_sequences=True, dropout=0.2, name='lstm_1'),

#     # Batch Normalization
#     BatchNormalization(name='batch_norm_1'),

#     # Second LSTM layer
#     LSTM(64, return_sequences=False, dropout=0.2, name='lstm_2'),

#     # Batch Normalization
#     BatchNormalization(name='batch_norm_2'),

#     # Dense layers
#     Dense(64, activation='relu', name='dense_1'),
#     Dropout(0.5, name='dropout_1'),

#     Dense(32, activation='relu', name='dense_2'),
#     Dropout(0.3, name='dropout_2'),

#     # Output layer
#     Dense(y.shape[1], activation='softmax', name='output')
# ])

model = Sequential()
model.add(Embedding(MAX_WORDS, 128, input_length=MAX_LEN))
model.add(LSTM(128, return_sequences=False))
model.add(Dropout(0.5))
model.add(Dense(64, activation="relu"))
model.add(Dense(y.shape[1], activation="softmax"))

# Build the model to initialize weights
model.build(input_shape=(None, MAX_LEN))

# Compile model
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

print("\n" + "="*60)
print("MODEL ARCHITECTURE")
print("="*60)
model.summary()
print("\n" + "="*60)

# ======================================================
# 9B. MODEL VISUALIZATION (Optional)
# ======================================================

from tensorflow.keras.utils import plot_model

# Save model architecture as image
plot_model(
    model,
    to_file='model_architecture.png',
    show_shapes=True,
    show_layer_names=True,
    rankdir='TB',  # Top to Bottom
    expand_nested=False,
    dpi=300
)

print("Model architecture diagram saved: model_architecture.png")
print("\n" + "="*60)

# ======================================================
# 10. SETUP CALLBACKS
# ======================================================

# Early Stopping: Stop training when validation loss doesn't improve
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1,
    mode='min'
)

# Model Checkpoint: Save best model during training
model_checkpoint = ModelCheckpoint(
    filepath='best_model.h5',
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1,
    mode='max'
)

# Reduce Learning Rate: Reduce LR when plateau detected
# reduce_lr = ReduceLROnPlateau(
#     monitor='val_loss',
#     factor=0.5,
#     patience=3,
#     min_lr=1e-7,
#     verbose=1,
#     mode='min'
# )

# callbacks = [early_stopping, model_checkpoint, reduce_lr]
callbacks = [early_stopping, model_checkpoint]

print("Callbacks configured:")
print("   - Early Stopping (patience=5)")
print("   - Model Checkpoint (save best model)")
print("   - Reduce Learning Rate (factor=0.5, patience=3)")
print("\n" + "="*60)

# ======================================================
# 11. MODEL TRAINING
# ======================================================

print("Starting model training...")
print("="*60)

history = model.fit(
    X_train, y_train,
    epochs=30,  # Will stop early if no improvement
    batch_size=64,
    validation_split=0.2,
    # callbacks=callbacks,
    verbose=1,
)

print("\n" + "="*60)
print("Training completed!")
print("="*60)

# ======================================================
# 12. MODEL EVALUATION (Comprehensive)
# ======================================================

print("📊 Evaluating model on test set...")
print("="*60)

# Evaluate on test set
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print(f"\n🎯 Test Accuracy: {acc:.4f}")
print(f"📉 Test Loss: {loss:.4f}")

# Generate predictions
y_pred = model.predict(X_test, verbose=0)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

# Classification Report
target_names = label_encoder.classes_
report = classification_report(y_true, y_pred_classes, target_names=target_names, output_dict=True)

print("\n" + "="*60)
print("CLASSIFICATION REPORT")
print("="*60)
print(classification_report(y_true, y_pred_classes, target_names=target_names))

# Save classification report
report_df = pd.DataFrame(report).transpose()
report_df.to_csv("classification_report.csv", index=True)
report_df.to_excel("classification_report.xlsx", index=True)
print("✔ Classification report saved (CSV & Excel)")

# Confusion Matrix
cm = confusion_matrix(y_true, y_pred_classes)

# Save confusion matrix
cm_df = pd.DataFrame(cm, index=target_names, columns=target_names)
cm_df.to_csv("confusion_matrix.csv")
cm_df.to_excel("confusion_matrix.xlsx")
print("✔ Confusion matrix saved (CSV & Excel)")

# Plot Confusion Matrix
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt="d",
            xticklabels=target_names,
            yticklabels=target_names,
            cmap='Blues',
            cbar_kws={'label': 'Count'})
plt.title("Confusion Matrix", fontsize=16, fontweight='bold')
plt.ylabel("True Label", fontsize=12)
plt.xlabel("Predicted Label", fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches='tight')
plt.show()
print("✔ Confusion matrix plot saved")

print("\n" + "="*60)

# ======================================================
# 13. TRAINING HISTORY VISUALIZATION
# ======================================================

print("📈 Plotting training history...")

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Plot Loss
axes[0].plot(history.history['loss'], label='Train Loss', linewidth=2)
axes[0].plot(history.history['val_loss'], label='Validation Loss', linewidth=2)
axes[0].set_title('Model Loss Over Epochs', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Epoch', fontsize=12)
axes[0].set_ylabel('Loss', fontsize=12)
axes[0].legend(loc='upper right')
axes[0].grid(True, alpha=0.3)

# Plot Accuracy
axes[1].plot(history.history['accuracy'], label='Train Accuracy', linewidth=2)
axes[1].plot(history.history['val_accuracy'], label='Validation Accuracy', linewidth=2)
axes[1].set_title('Model Accuracy Over Epochs', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Epoch', fontsize=12)
axes[1].set_ylabel('Accuracy', fontsize=12)
axes[1].legend(loc='lower right')
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("training_history.png", dpi=300, bbox_inches='tight')
plt.show()

print("✔ Training history plot saved")
print("\n" + "="*60)

# ======================================================
# 14. SAVE MODEL & ARTIFACTS
# ======================================================

print("💾 Saving model and artifacts...")
print("="*60)

# 1. Save the trained model
model.save("modsec_lstm_model.h5")
print("✔ Model saved: modsec_lstm_model.h5")

# 2. Save tokenizer
with open('tokenizer.pickle', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)
print("✔ Tokenizer saved: tokenizer.pickle")

# 3. Save label encoder
with open('label_encoder.pickle', 'wb') as handle:
    pickle.dump(label_encoder, handle, protocol=pickle.HIGHEST_PROTOCOL)
print("✔ Label encoder saved: label_encoder.pickle")

# 4. Save hyperparameters
hyperparameters = {
    'MAX_WORDS': MAX_WORDS,
    'MAX_LEN': MAX_LEN,
    'num_classes': len(label_encoder.classes_),
    'classes': label_encoder.classes_.tolist(),
    'vocab_size': len(tokenizer.word_index),
    'test_accuracy': float(acc),
    'test_loss': float(loss)
}

with open('hyperparameters.json', 'w') as f:
    json.dump(hyperparameters, f, indent=4)
print("✔ Hyperparameters saved: hyperparameters.json")

# 5. Save training history
history_dict = {
    'loss': [float(x) for x in history.history['loss']],
    'val_loss': [float(x) for x in history.history['val_loss']],
    'accuracy': [float(x) for x in history.history['accuracy']],
    'val_accuracy': [float(x) for x in history.history['val_accuracy']]
}

with open('training_history.json', 'w') as f:
    json.dump(history_dict, f, indent=4)
print("✔ Training history saved: training_history.json")

print("\n" + "="*60)
print("✅ ALL ARTIFACTS SAVED SUCCESSFULLY!")
print("="*60)
print("\nSaved files:")
print("  1. modsec_lstm_model.h5          - Trained model")
print("  2. best_model.keras              - Best model checkpoint")
print("  3. tokenizer.pickle              - Text tokenizer")
print("  4. label_encoder.pickle          - Label encoder")
print("  5. hyperparameters.json          - Model configuration")
print("  6. training_history.json         - Training metrics")
print("  7. classification_report.csv     - Evaluation metrics")
print("  8. confusion_matrix.png          - Confusion matrix plot")
print("  9. training_history.png          - Training curves")
print("\n" + "="*60)

"""------------------------------------------------------------------------------------"""

# ======================================================
# 15. INFERENCE FUNCTION (For Production Use)
# ======================================================

def load_model_artifacts():
    """
    Load all saved model artifacts for inference

    Returns:
        model: Trained Keras model
        tokenizer: Fitted tokenizer
        label_encoder: Fitted label encoder
        hyperparams: Model hyperparameters
    """
    from tensorflow.keras.models import load_model

    # Load model
    model = load_model('modsec_lstm_model.h5')

    # Load tokenizer
    with open('tokenizer.pickle', 'rb') as handle:
        tokenizer = pickle.load(handle)

    # Load label encoder
    with open('label_encoder.pickle', 'rb') as handle:
        label_encoder = pickle.load(handle)

    # Load hyperparameters
    with open('hyperparameters.json', 'r') as f:
        hyperparams = json.load(f)

    return model, tokenizer, label_encoder, hyperparams


def predict_attack(text_input, model, tokenizer, label_encoder, max_len):
    """
    Predict attack type from log text

    Args:
        text_input: Raw log text (string or list of strings)
        model: Trained model
        tokenizer: Fitted tokenizer
        label_encoder: Fitted label encoder
        max_len: Maximum sequence length

    Returns:
        predictions: List of (label, confidence) tuples
    """
    # Ensure input is a list
    if isinstance(text_input, str):
        text_input = [text_input]

    # Clean text (apply same preprocessing)
    # cleaned_texts = [clean_text(text) for text in text_input]

    # Tokenize and pad
    sequences = tokenizer.texts_to_sequences(text_input)
    padded = pad_sequences(sequences, maxlen=max_len, padding='post', truncating='post')

    # Predict
    predictions = model.predict(padded, verbose=0)

    # Get predicted classes and confidences
    results = []
    for pred in predictions:
        predicted_class = np.argmax(pred)
        confidence = pred[predicted_class]
        label = label_encoder.classes_[predicted_class]
        results.append((label, confidence))

    return results

print("✔ Inference functions defined")
print("\nUsage example:")
print("  model, tokenizer, label_encoder, params = load_model_artifacts()")
print("  result = predict_attack(log_text, model, tokenizer, label_encoder, params['MAX_LEN'])")
print("\n" + "="*60)

# ======================================================
# 16. INFERENCE DEMO
# ======================================================

print("🔍 Running inference demo...")
print("="*60)

# Test with sample data from test set
sample_indices = np.random.choice(len(X_test), 20, replace=False)

print("\nPrediction Results:")
print("-" * 80)

for idx in sample_indices:
    # Get original text
    original_text = df.iloc[idx]['text'][:200] + "..."

    # True label
    true_label = label_encoder.classes_[y_true[idx]]

    # Predict
    result = predict_attack(original_text, model, tokenizer, label_encoder, MAX_LEN)
    pred_label, confidence = result[0]

    # Display
    print(f"\n📝 Text: {original_text}")
    print(f"✅ True Label: {true_label}")
    print(f"🎯 Predicted: {pred_label} (Confidence: {confidence:.2%})")
    print(f"{'✔ CORRECT' if pred_label == true_label else '✘ INCORRECT'}")
    print("-" * 80)